### ISSUE TITLE
Missing new layout for Australia

### ISSUE THREAD

**Issue by BrightDV** [bacinger/f1-circuits#3]
Hi!
Firstly, thanks a lot for these very useful files, I'm using them in my app to show the track layout, and currently to have a replay of the races.
However, I just figured out that the new turn in Australia is missing:
- [The layout present in this repo looks like that](https://github.com/bacinger/f1-circuits/blob/master/circuits/au-1953.geojson):
![image](https://github.com/bacinger/f1-circuits/assets/92821484/05edaed6-f35f-4f87-b162-6f4126aabd1e)
- However, the new layout looks like this:
<img src="https://github.com/bacinger/f1-circuits/assets/92821484/9a2066cd-6f4c-4072-9f1c-c24dc176b785" height=300>

I think that the track should follow the road (Lakeside Drive) between turn 8 and turn 9.
Thanks!

**Comment by bacinger** [comment]
Hi BrightDV,

Thank you for raising this issue. Indeed, the circuit layout has changed in 2022. 

I updated the track file.
