### ISSUE TITLE
ETA on 2024 tracks ?

### ISSUE THREAD

**Issue by glensargent** [bacinger/f1-circuits#4]
Hey! Do you have any eta on the upcoming tracks for this years f1? Such as Saudi Arabia

Also any information on how you get your data so that we can contribute would be great, cheers

**Comment by bacinger** [comment]
Hey. For all upcoming 2024 seasons, all the tracks are available in the repository. You can see the championship here: https://github.com/bacinger/f1-circuits/blob/master/championships/f1-locations-2024.json.

Specifically, here is the Saudi Arabian Grand Prix track: https://github.com/bacinger/f1-circuits/blob/master/circuits/sa-2021.geojson
